### ISSUE TITLE
Module not found: Error: Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by petricachiriac** [sujith3g/docxtemplater-link-module#1]
Can we remove 
fs = require('fs'); from 

here
https://github.com/sujith3g/docxtemplater-link-module/blob/master/index.js#L7
and
have this dependence only for testing.

On build I have this error:

```
ERROR in ./~/docxtemplater-link-module/index.js
Module not found: Error: Cannot resolve module 'fs' in /builds/web-project/node_modules/docxtemplater-link-module
 @ ./~/docxtemplater-link-module/index.js 7:5-18
```

**Comment by sujith3g** [comment]
Removed it, `fs` only required for testing

**Comment by petricachiriac** [comment]
:+1: is working perfect now! Thanks!
